INSERT INTO CUSTOMER(EMAIL_ADDRESS, MARKETING_SCORE) VALUES ('slee@14west.us', 10);
INSERT INTO CUSTOMER(EMAIL_ADDRESS, MW_LISTS_COUNT, MW_SUBS_COUNT, MARKETING_SCORE) VALUES ('aquire@14west.us', 0, 0, 0);
INSERT INTO CUSTOMER(EMAIL_ADDRESS, MW_LISTS_COUNT, MW_SUBS_COUNT, MARKETING_SCORE) VALUES ('convert@14west.us', 5, 2, 0);
INSERT INTO CUSTOMER(EMAIL_ADDRESS, BS_LAST_PURCHASE_SINCE, BS_LIFETIME_REVENUE, BS_LIFETIME_VISITS, MW_LISTS_COUNT, MW_SUBS_COUNT, MARKETING_SCORE) VALUES ('adopt@14west.us', 1, 5000 ,100, 5, 2, 0);
INSERT INTO CUSTOMER(EMAIL_ADDRESS, BS_LAST_PURCHASE_SINCE, BS_LIFETIME_REVENUE, BS_LIFETIME_VISITS, MW_LISTS_COUNT, MW_SUBS_COUNT, BS_PREDICTIVE_PURCHASE_INTENT, BS_PREDICTIVE_ENGAGEMENT_PERCENTILE, MARKETING_SCORE) VALUES ('engage@14west.us', 1, 5000 ,100, 5, 2, 100, 100, 0);
-- INSERT INTO CUSTOMER(EMAIL_ADDRESS, BS_LAST_PURCHASE_SINCE, BS_LIFETIME_REVENUE, BS_LIFETIME_VISITS, BS_PREDICTIVE_PURCHASE_INTENT, BS_PREDICTIVE_RETENTION, MW_LISTS_COUNT, MW_SUBS_COUNT)